In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import  Dense
import pickle

In [ ]:
dataframe=pd.read_csv(r'C:\Users\sangu\Downloads\dataset1.csv',sep=',')

#dataframe = dataframe.drop('GE1DER',axis =1)
dataframe = dataframe.drop('LOCALITY',axis =1)
#dataframe = dataframe.drop(labels=23, axis=0)
print(dataframe.shape)

dataset=dataframe.values
print(dataset)


In [3]:
dataframe


AGE  HEIGHT  weight  GENDER  TRAVELLED/NOT  TIERDNESS  F_DAYS  F_TEMP  \
0      12     137      38       0              0          0       2      99   
1      12     137      38       0              0          0       2      99   
2      12     137      38       0              0          0       2      99   
3      12     137      38       0              0          0       2      99   
4      12     137      38       0              0          0       2      99   
...   ...     ...     ...     ...            ...        ...     ...     ...   
6235   45     177      73       1              1          1       3     100   
6236   45     177      73       0              0          1       3      99   
6237   45     177      73       0              1          1       3     100   
6238   45     178      73       1              0          1       3      99   
6239   45     178      73       1              1          1       3     100   

      COLD_TYPE  COLD_DAYS  COUGH_TYPE  COUGH_DAYS  DIARRHEA_TYPE  VOMIT  \
0             0          0           0           0              0      0   
1             1          0           0           0              0      0   
2             0          0           0           0              0      0   
3             0          0           0           0              0      0   
4             0          0           0           0              0      0   
...         ...        ...         ...         ...            ...    ...   
6235          1          1           1           1              1      1   
6236          1          1           1           1              1      1   
6237          1          1           1           1              1      1   
6238          1          1           1           1              1      1   
6239          1          1           1           1              1      1   

      BODYACHE  PRESCRIPTION  Result  
0            0             1      51  
1            0             1      51  
2            0             1      51  
3            1             2      52  
4            1             2      52  
...        ...           ...     ...  
6235         1            15     133  
6236         1            15     133  
6237         1            15     133  
6238         1            15     133  
6239         1            15     133  

[6240 rows x 17 columns]

In [4]:
x=dataset[:,0:15]
#x=np.asarray(x).astype(np.int64)
print(x.shape)
print(x)
y=dataset[:,-1]
#from sklearn.preprocessing import LabelEncoder
#lb=LabelEncoder()
#y=lb.fit_transform(y)
print(y)
y=np.reshape(y, (-1,1))
print(y.shape)

(6240, 15)
[[ 12 137  38 ...   0   0   0]
 [ 12 137  38 ...   0   0   0]
 [ 12 137  38 ...   0   0   0]
 ...
 [ 45 177  73 ...   1   1   1]
 [ 45 178  73 ...   1   1   1]
 [ 45 178  73 ...   1   1   1]]
[ 51  51  51 ... 133 133 133]
(6240, 1)


In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y)
#x_train=np.asarray(x_train).astype(np.int64)

In [6]:
model=Sequential()
model.add(Dense(12,input_dim=15,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='linear'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 12)                192       
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9         
Total params: 305
Trainable params: 305
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.compile(loss='mse',optimizer='adam',metrics=['mse','mae'])


In [ ]:
model= model.fit(x_train,y_train,epochs=10,batch_size=20,validation_steps=1,verbose='auto')

Epoch 1/10
234/234 [==============================] - 1s 2ms/step - loss: 51.2801 - mse: 51.2801 - mae: 5.5512
Epoch 2/10
234/234 [==============================] - 1s 2ms/step - loss: 38.0813 - mse: 38.0813 - mae: 4.7065
Epoch 3/10
234/234 [==============================] - 1s 2ms/step - loss: 27.3461 - mse: 27.3461 - mae: 3.8751
Epoch 4/10
234/234 [==============================] - 1s 2ms/step - loss: 19.9905 - mse: 19.9905 - mae: 3.2610
Epoch 5/10
234/234 [==============================] - 1s 2ms/step - loss: 15.5466 - mse: 15.5466 - mae: 2.8188
Epoch 6/10
234/234 [==============================] - 1s 3ms/step - loss: 13.2706 - mse: 13.2706 - mae: 2.5753
Epoch 7/10
234/234 [==============================] - 1s 2ms/step - loss: 12.0706 - mse: 12.0706 - mae: 2.4306
Epoch 8/10
 69/234 [=======>......................] - ETA: 0s - loss: 11.6051 - mse: 11.6051 - mae: 2.3978

In [17]:
xnew=np.array([[12,137,38,0,0,0,2,102,0,0,0,0,0,0,0]])
ynew= model.predict(xnew)
print(ynew)
print("X=%s, Predicted=%s" % (xnew[0], ynew[0]))

[[68.67813]]
X=[ 12 137  38   0   0   0   2 102   0   0   0   0   0   0   0], Predicted=[68.67813]


In [10]:
model.save('model_predict.h5')

In [11]:
from tensorflow.python import keras
import tensorflow

modelnew = keras.models.load_model('model_predict.h5')
converter=tensorflow.lite.TFLiteConverter.from_keras_model(modelnew)
tflite_model = converter.convert()
open("nobel_ml.tflite", "wb").write(tflite_model)

INFO:tensorflow:Assets written to: C:\Users\sangu\AppData\Local\Temp\tmpyw0a4ord\assets


3100

In [15]:
xnew=np.array([[12,137,38,0,0,0,2,99,0,0,0,0,0,0,0]])
ynew= modelnew.predict(xnew)
print("X=%s, Predicted=%s" % (xnew[0], ynew[0]))

X=[ 12 137  38   0   0   0   2  99   0   0   0   0   0   0   0], Predicted=[68.692825]


In [24]:
import pandas as pd
import pickle
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
pickle.dump(tflite_model, open('model.pkl', 'wb')
model=pickle.load(open('model.pkl', 'rb')
print(model.predict([[12,137,38,0,0,0,2,99,0,0,0,0,0,0,0]]))

SyntaxError: invalid syntax (3085187228.py, line 6)